AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'spec/**/*'
    - 'vendor/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Lint/NestedPercentLiteral:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false
